name: BlockLagFix
main: JavierLeon9966\BlockLagFix\BlockLagFix
author: JavierLeon9966
version: 1.6.0
api: 4.0.0
mcpe-protocol: [431, 440, 448, 465, 471, 475, 486, 503, 527, 534, 544, 545, 554, 557]
description: Fixes block lagging
